package com.muyi.numbers.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.muyi.numbers.entity.District;

import com.muyi.numbers.greendao.DistrictDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig districtDaoConfig;

    private final DistrictDao districtDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        districtDaoConfig = daoConfigMap.get(DistrictDao.class).clone();
        districtDaoConfig.initIdentityScope(type);

        districtDao = new DistrictDao(districtDaoConfig, this);

        registerDao(District.class, districtDao);
    }
    
    public void clear() {
        districtDaoConfig.clearIdentityScope();
    }

    public DistrictDao getDistrictDao() {
        return districtDao;
    }

}
